---
kind: pipeline
name: default

steps:
  - name: build
    image: golang:1.21.2
    volumes:
      - name: deps
        path: /go
    commands:
      - make

  - name: test
    image: golang:1.21.2
    volumes:
      - name: deps
        path: /go
    commands:
      - make test

  - name: linter
    image: golang:1.21.2
    volumes:
      - name: deps
        path: /go
    commands:
      - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s
      - ./bin/golangci-lint run --timeout 5m
      - rm -r ./bin/

  - name: docker latest
    image: plugins/docker
    settings:
      username: depado
      password:
        from_secret: ghcr_pat
      repo: ghcr.io/depado/platypus
      registry: ghcr.io
      tags:
        - latest
        - "${DRONE_COMMIT_SHA}"
      build_args:
        - version="latest"
        - build="${DRONE_COMMIT_SHA}"
    when:
      event: [push]
      branch: [main]

  - name: docker tag
    image: plugins/docker
    settings:
      username: depado
      password:
        from_secret: ghcr_pat
      repo: ghcr.io/depado/platypus
      registry: ghcr.io
      tags:
        - latest
        - "${DRONE_TAG}"
        - "${DRONE_COMMIT_SHA}"
      build_args:
        - version="${DRONE_TAG}"
        - build="${DRONE_COMMIT_SHA}"
    when:
      event: [tag]

  - name: release
    image: golang:1.21.2
    environment:
      TAG: "${DRONE_TAG}"
      BUILD: "${DRONE_COMMIT_SHA}"
      GITHUB_TOKEN:
        from_secret: github_token
    volumes:
      - name: deps
        path: /go
    commands:
      - curl -sL https://git.io/goreleaser | bash
    when:
      event: [tag]

  - name: telegram
    image: appleboy/drone-telegram
    settings:
      to: 790376882
      format: markdown
      token:
        from_secret: telegram_token
      message: >
        *{{repo.name}}*
        [Build {{build.number}}]({{build.link}}) by {{commit.author}} {{#success build.status}}succeeded{{else}}failed{{/success}} in {{buildtime build.started}}
        `{{truncate commit.sha 8}}`: "{{commit.message}}"
    when:
      status:
        - success
        - failure

volumes:
  - name: deps
    host:
      path: /var/lib/cache/godeps/
